### ISSUE TITLE
[BUG] Complement specification regarding Events

### ISSUE THREAD

**Issue by atextor** [eclipse-esmf/esmf-semantic-aspect-meta-model#104]
**Describe the bug**
Events are mentioned in the [meta model elements overview](https://openmanufacturingplatform.github.io/sds-bamm-aspect-meta-model/bamm-specification/snapshot/meta-model-elements.html), however, the textual specification is inconsistent with the diagram:
* In section [Declaring Aspects](https://openmanufacturingplatform.github.io/sds-bamm-aspect-meta-model/bamm-specification/snapshot/modeling-guidelines.html#declaring-aspects) the attribute `bamm:events` from the meta model elements overview diagram is not mentioned (neither mandatory nor optional)
* There is no section "Declaring Events"
* Semantics of Events are not defined sufficiently. In particular the [Payloads](https://openmanufacturingplatform.github.io/sds-bamm-aspect-meta-model/bamm-specification/snapshot/payloads.html) section should mention if and how events are part of runtime payloads, i.e., how is an Event different from an Entity.

**Screenshots**
![image](https://user-images.githubusercontent.com/1199036/153140639-c7bf754a-541d-463d-9ddf-7ec8af40229f.png)
![image](https://user-images.githubusercontent.com/1199036/153140821-a8689088-76ab-4340-8807-f364a688bcbf.png)

**Comment by atextor** [comment]
WG discussion 2022-02-24: BAMM payload mapping corresponds to Asset Administration Shell "value only" serialization, which means that events are not part of the runtime payloads.

**Comment by BirgitBoss** [comment]
Also consider to change meta model overview figure: there should be an aggregation from Event to Property.

**Comment by NicoMakowe** [comment]
In the overview diagram, the aggregation `parameters ` should point to Event instead of Operation.
