### ISSUE TITLE
[Task] Example with instance data

### ISSUE THREAD

**Issue by kenwenzel** [eclipse-esmf/esmf-semantic-aspect-meta-model#121]
**Is your task related to a problem? Please describe.**
When studying the BAMM documentation I couldn't find any example with instance data. The given examples only cover modeling vocabulary but no instances that use the defined vocabulary.

**Describe the solution you'd like**
Provide a basic example that covers the vocabulary and instance data.

**Comment by BirgitBoss** [comment]
Hi,  @kenwenzel 
in the chapter https://openmanufacturingplatform.github.io/sds-documentation/bamm-specification/snapshot/modeling-guidelines.html there are many examples for semantic definitions using the characteristics etc.

But you probably refer to instance data like you get in the payload of a REST API. This is defined in https://openmanufacturingplatform.github.io/sds-documentation/bamm-specification/snapshot/payloads.html but you are right, there is only one small example in it.

I recommend to use the free aspect model editor, it includes a more complex example and you are guided in editing new models and then can have a look at the .ttl [tps://www.bosch-connected-industry.com/de/en/services/downloads/aspect-model-editor/](https://www.bosch-connected-industry.com/de/en/services/downloads/aspect-model-editor/) 
We hope to have an open source editor soon.

An example is also used in the whitepaper https://open-manufacturing.org/wp-content/uploads/sites/101/2021/09/OMP-Semantic-Data-Structuring-Whitepaper.pdf

**Comment by BirgitBoss** [comment]
I recommend to add a complete payload example using the main characteristics into the payload chapter. Just use the Movement example from the free aspect model editor.
