### ISSUE TITLE
[Task] Asset Administration Shell - describe semantics of ReferenceElement submodel element

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-esmf/esmf-semantic-aspect-meta-model#138]
**Is your task related to a problem? Please describe.**
SAMM shall support the semantic definition of reference element submodel elements in the Asset Administration Shell (AAS).

**Describe the solution you'd like**
introduce characteristic for references
introduce characteristic for model references
introduce characteristic for global references

Note: in AAS a reference may be either a global reference like an urn or it may be a reference to a property of another aspect in another twin. There are also requirements to state: it is a reference to the element with the semanticId XYZ in the aspect 123.

**Describe alternatives you've considered**
none

**Additional context**
compare to #133 (relationship element)
https://industrialdigitaltwin.org/wp-content/uploads/2021/09/07_details_of_the_asset_administration_shell_part1_v3_en_2020.pdf

**Comment by BirgitBoss** [comment]
This would be a straightforward modelling (AAS V3.0 DRAFT). However, it contains a recursion (type Reference for referredSemanticId):

:Reference a bamm:Entity;
    bamm:properties (:keys :type :referredSemanticId);
    bamm:preferredName "Reference"@en.
:ReferenceCharacteristic a bamm:Characteristic;
    bamm:dataType :Reference.
:keys a bamm:Property;
    bamm:characteristic :ListOfKeys.
:ListOfKeys a bamm-c:List;
    bamm:dataType :Key.
:Key a bamm:Entity;
    bamm:properties (:keyType :value).
:value a bamm:Property;
    bamm:characteristic :Identifier.
:type a bamm:Property;
    bamm:characteristic :ReferenceTypes;
    bamm:exampleValue "ExternalReference".
:referredSemanticId a bamm:Property;
    bamm:characteristic :ReferenceCharacteristic.
:ReferenceTypes a bamm-c:Enumeration;
    bamm:dataType xsd:string;
    bamm-c:values ("ExternalReference" "ModelReference").
:keyType a bamm:Property;
    bamm:characteristic :KeyTypesEnum.
:Identifier a bamm-c:Code;
    bamm:dataType xsd:string.
:KeyTypesEnum a bamm-c:Enumeration;
    bamm:dataType xsd:string;
    bamm-c:values ("AnnotationRelationshipElement" "AssetAdministrationShell" "BasicEventElement" "Blob" "Capability" "ConceptDescription" "DataElement" "Entity" "EventElement" "File" "FragmentReference" "GlobalReference" "Identifiable" "MultiLanguageProperty" "Operation" "Property" "Range" "Referable" "ReferenceElement" "RelationshipElement" "Submodel" "SubmodelElement" "SubmodelElementCollection" "SubmodelElementList").

**Comment by chris-volk** [comment]
@atextor , should there be an ADR to describe how this and other Asset Administration Shell features are supported within SAMM and tooling?
