### ISSUE TITLE
[Task] Define naming convention for Events

### ISSUE THREAD

**Issue by atextor** [eclipse-esmf/esmf-semantic-aspect-meta-model#147]
**Is your task related to a problem? Please describe.**
In [Namespaces and Versions](https://openmanufacturingplatform.github.io/sds-bamm-aspect-meta-model/bamm-specification/snapshot/namespaces.html#aspect-model-element-identifiers-definition), naming conventions for model elements are defined:
> element-name — The name of the element:
>   For Aspects, Entities and Characteristics, the name must be given in [UpperCamelCase](https://en.wikipedia.org/wiki/Camel_case)
>   For Properties, Operations and Units, the name must be given in [lowerCamelCase](https://en.wikipedia.org/wiki/Camel_case)

Hoever, no naming convention is defined for Events.

**Describe the solution you'd like**
Add Events to one of the lists (either UpperCamelCase or LowerCamelCase).

**Comment by chris-volk** [comment]
Decision @atextor and @chris-volk : Events must be given in UpperCamelCase starting with the next major SAMM release. Reasoning: They are structurally identical to Entities (containing Properties)

**Comment by atextor** [comment]
Fixed by #237
