### ISSUE TITLE
[BUG] `samm:curie` + `samm-c:UnitReference`: Explicitly specify how prefixes are interpreted

### ISSUE THREAD

**Issue by atextor** [eclipse-esmf/esmf-semantic-aspect-meta-model#252]
**Describe the bug**
The [samm:curie](https://eclipse-esmf.github.io/samm-specification/2.1.0/datatypes.html) data type refers to the [CURIE](https://www.w3.org/TR/curie/) specification, which allows definition of CURIES in the form `foo:bar`, `:bar` and also `bar` (i.e., without prefix and colon).

Generally, when `samm:curie` is used, it is currently not explicitly defined how the curie is resolved (at run time). The spec needs to make clear that the runtime value is to be interpreted as if it appears in the context of the model. It needs to define how leaving out the prefix is to be interpreted (since [@base and relative IRIs](https://www.w3.org/TR/turtle/#relative-iri) are not used in Aspect Models), or if it is disallowed altogether.

Specifically, for the [samm-c:UnitReference](https://eclipse-esmf.github.io/samm-specification/2.1.0/characteristics.html#unit-reference-characteristic) Characteristic, currently only references to SAMM's Unit catalog [are allowed](https://eclipse-esmf.github.io/samm-specification/2.1.0/modeling-guidelines.html#using-unit-reference):

> The runtime payload refers to the unit using its samm:curie, i.e., the unit’s URN’s element name prefixed with `unit:`.

This information should be made more obvious.

**Comment by chris-volk** [comment]
@michelu89 , can you please check in the Aspect Model Editor?
