### ISSUE TITLE
[BUG] Curie enumeration fails in SAMM SDK 2.3.1

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-esmf/esmf-semantic-aspect-meta-model#259]
**Describe the bug**
The model in this [PR ](https://github.com/eclipse-tractusx/sldt-semantic-models/pull/299) uses a curie for enumeration which validates fine in aspect model editor v 4.5.2.

See validation in this [github action run](https://github.com/eclipse-tractusx/sldt-semantic-models/actions/runs/6570420148/job/17847811347?pr=299).

**Where**
See stage "Validate semantic models": 

Starting download of SAMM SDK v2.3.1
Downloaded SAMM SDK v2.3.1
Validating TTL file io.catenax.shared.quantity/1.0.0/Quantity.ttl
[
  {
    file: 'io.catenax.shared.quantity/1.0.0/Quantity.ttl',
    response: 'Validation failed:\n' +
      'Validation succeeded, but an error was found while processing the model. This indicates an error in the model validation; please consider reporting this issue including the model at https://github.com/eclipse-esmf/esmf-semantic-aspect-meta-model/issues -- Could not load Aspect model, please make sure the model is valid: Literal can not be parsed: unit:piece^^urn:samm:org.eclipse.esmf.samm:meta-model:2.0.0#curie\n' +
      '\n'
  }
]

**Screenshots**
not applicable

**Additional context**
An enumeration with curie is used to allow different types of units of measure.

**Comment by chris-volk** [comment]
Hi @tom-rm-meyer-ISST , 
I created a bug in the sdk repository: https://github.com/eclipse-esmf/esmf-sdk/issues/454 .

When you identify bugs in the SDK, please use that repository if possible (unless it is clear that the SAMM specification or its SHACL shapes themselves are the originator of the improvement/bug)

**Comment by chris-volk** [comment]
> Hi @tom-rm-meyer-ISST , I created a bug in the sdk repository: [eclipse-esmf/esmf-sdk#454](https://github.com/eclipse-esmf/esmf-sdk/issues/454) .
> 
> When you identify bugs in the SDK, please use that repository if possible (unless it is clear that the SAMM specification or its SHACL shapes themselves are the originator of the improvement/bug)

Never mind, I have now read the message and this is exactly the case. thanks for reporting it in samm.

**Comment by tom-rm-meyer-ISST** [comment]
> > Hi @tom-rm-meyer-ISST , I created a bug in the sdk repository: [eclipse-esmf/esmf-sdk#454](https://github.com/eclipse-esmf/esmf-sdk/issues/454) .
> > 
> > When you identify bugs in the SDK, please use that repository if possible (unless it is clear that the SAMM specification or its SHACL shapes themselves are the originator of the improvement/bug)
> 
> Never mind, I have now read the message and this is exactly the case. thanks for reporting it in samm.

I blindly followed the hint in the GitHub action. Therefore: thanks for emphasizing!

**Comment by ysrbo** [comment]
was fixed in  [sdk#382
](https://github.com/eclipse-esmf/esmf-sdk/issues/382)
