### ISSUE TITLE
[Task] Update site notice

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-esmf/esmf-semantic-aspect-meta-model#269]
It seems the site notice is outdated because it still mentions OMP:

https://github.com/eclipse-esmf/esmf-semantic-aspect-meta-model/blob/main/documentation/modules/legal/pages/site-notice.adoc

remove first sentence: This is an approved deliverable by the [Open Manufacturing Platform (OMP)](https://open-manufacturing.org/).

**Comment by atextor** [comment]
Closing: site-notice.adoc does not exist any longer.
