### ISSUE TITLE
[BUG] Example Versioning and openAPI generation seems not to be consistent?

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-esmf/esmf-semantic-aspect-meta-model#308]
https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/samm-cli.html#naming-and-versioning

```
{
  "openapi" : "3.0.3",
  "info" : {
    "title" : "TestAspect",  
    "version" : "v2" 
  }
}
```

The example for openAPI generation seems wrong: shouldn't it be `V1 `since it is

`@prefix : <urn:samm:com.mycompany.myapplication:1.0.0#>`
?

**Comment by Yauhenikapl** [comment]
Resolved in this PR: https://github.com/eclipse-esmf/esmf-sdk/issues/636

Thanks!
