### ISSUE TITLE
[BUG] Update Time Series example

### ISSUE THREAD

**Issue by VladimirAlexiev** [eclipse-esmf/esmf-semantic-aspect-meta-model#313]
https://eclipse-esmf.github.io/samm-specification/2.1.0/modeling-guidelines.html#declaring-time-series

A: Why `samm-e:value` is not used?
> The [TimeSeriesEntity](https://eclipse-esmf.github.io/samm-specification/2.1.0/entities.html#time-series-entity) is declared as an Abstract Entity. It .. defines value as an [Abstract Property](https://eclipse-esmf.github.io/samm-specification/2.1.0/modeling-guidelines.html#abstract-entities-with-abstract-properties), i.e., a Property without a Characteristic.

`TimeSeriesEntity` has props `samm-e:timestamp, samm-e:value`.

Example:
```ttl
:MachineStateTimeSeriesEntity a samm:Entity ;
   samm:extends samm-e:TimeSeriesEntity ;
   samm:properties ( :machineState ) .
```

So `MachineStateTimeSeriesEntity` reuses `samm-e:timestamp`; but defines its own concrete prop `:machineState`, therefore it gives up on `samm-e:value`.
Why is that? In contrast, https://eclipse-esmf.github.io/samm-specification/2.1.0/modeling-guidelines.html#abstract-entities-with-abstract-properties reuses two defined abstract props and concretizes them as:
```ttl
   samm:properties (
     [ samm:extends :x ; samm:characteristic :IntegerNumber ]
     [ samm:extends :y ; samm:characteristic :IntegerNumber ]
```

A1: `:MachineStateTimeSeriesEntity samm:extends samm-e:TimeSeriesEntity` so it must have `samm-e:value`, right?
But it leaves `samm-e:value` abstract, so doesn't that mean that `:MachineStateTimeSeriesEntity` cannot be instantiated?

B: How to represent timeseries with multiple values?
A common case is to have timeseries with multiple value columns correlated on the same timestamp.
How would this case be represented? I can define multiple value props in a concrete TimeSeries, but given the "special status" of `samm-e:value`, how exactly will that work?
Please give a new example.

**Comment by atextor** [comment]
Hi @VladimirAlexiev,
you are absolutely correct: The TimeSeries example predates the introduction of Abstract Entities and was not updated.

The example should therefore not introduce a separate `machineState` Property but should instead look like this:

```turtle
:MachineStateTimeSeries a samm-c:TimeSeries ;
   samm:dataType :MachineStateTimeSeriesEntity .

:MachineStateTimeSeriesEntity a samm:Entity ;
   samm:extends samm-e:TimeSeriesEntity ;
   samm:properties ( 
     [ samm:extends samm-e:value ; samm:characteristic :MachineState ]
   ) .

:MachineState a samm-c:State ;
   samm:dataType xsd:string ;
   samm-c:defaultValue "STANDBY" ;
   samm-c:values ( "RUNNING" "STANDBY" "OFF" ) .
```

Regarding your second question, how is a time series with multiple values represented: This is done by using a Characteristic with a complex (Entity) data type. An example for this could look like this:

```turtle
:sensorValues a samm:Property ;
  samm:characteristic :SensorValues .

:SensorValues a samm-c:TimeSeries ;
  samm:dataType :SensorMeasurementTimeSeriesEntity .

:SensorMeasurementTimeSeriesEntity a samm:Entity ;
  samm:extends samm-e:TimeSeriesEntity ;
  samm:properties (
    [ samm:extends samm-e:value ; samm:characteristic :SingleSensorMeasurement ]
  ) .

:SingleSensorMeasurement a samm-c:SingleEntity ;
  samm:dataType :SensorMeasurement .

:SensorMeasurement a samm:Entity ;
  samm:properties ( :temperature :pressure ) .

:temperature a samm:Property ;
  samm:characteristic [
    a samm-c:Measurement ;
    samm:dataType xsd:float ;
    samm-c:unit unit:degreeCelsius ;
  ] .

:pressure a samm:Property ;
  samm:characteristic [
    a samm-c:Measurement ;
    samm:dataType xsd:float ;
    samm-c:unit unit:hectopascal ;
  ] .
```

The corresponding JSON data would then look like this:

```json
{
  "sensorValues": [
    {
      "timestamp": "2024-12-09T14:23:00",
      "value": {
        "temperature": 13.0,
        "pressure": 1018
      }
    },
    {
      "timestamp": "2024-12-09T14:24:00",
      "value": {
        "temperature": 13.1
        "pressure": 1019
      }
    }
  ]
}
```
