### ISSUE TITLE
[Task] Provide Best Practices

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-esmf/esmf-semantic-aspect-meta-model#68]
**Is your task related to a problem? Please describe.**
As a user of BAMM for modeling, e.g. in CATENA-X, it would be very helpful to have some best practice advices.

**Describe the solution you'd like**
Document with best practices how to model with BAMM

**Describe alternatives you've considered**
Alternatively or complementary also a FAQ might be useful. Similar to https://github.com/admin-shell-io/questions-and-answers

**Comment by atextor** [comment]
Working group discussion on 2022-01-27: Create infrastructure for a "Best Practices" document as a separate documentation module. Write initial content, which should be reviewed by the WG before merging.
